// Раскомментированы только проверенные иконки в assets/icons. Проверять рендеринг можно в сторибуке
const IconMapping = {
  pointingHand: 'cursor/pointing-hand.svg',
  // notificationsDigit: '14x14/common/notifications.svg',
  syncDone: '16x16/sync/done.svg',
  syncUpdate: '16x16/sync/update.svg',
  chevronDown: '20x20/chevron/down.svg',
  chevronUp: '20x20/chevron/up.svg',
  // mapPin: '24x24/add block/map-pin.svg',
  // api: '24x24/add-block/api.svg',
  // creditCard: '24x24/add-block/credit-card.svg',
  // deeplink: '24x24/add-block/deeplink.svg',
  // gitBranch: '24x24/add-block/git-branch.svg',
  // headphones: '24x24/add-block/headphones.svg',
  // messageSquare: '24x24/add-block/message-square.svg',
  // sliders: '24x24/add-block/sliders.svg',
  // table: '24x24/add-block/table.svg',
  // button: '24x24/add-content/button.svg',
  // file: '24x24/add-content/file.svg',
  // image: '24x24/add-content/image.svg',
  // music: '24x24/add-content/music.svg',
  // video: '24x24/add-content/video.svg',
  // calendar: '24x24/common/calendar.svg',
  // check: '24x24/common/check.svg',
  // chevronBig: '24x24/common/chevron-big.svg',
  // close: '24x24/common/close.svg',
  // cloud: '24x24/common/cloud.svg',
  // copy: '24x24/common/copy.svg',
  // export: '24x24/common/export.svg',
  // filter: '24x24/common/filter.svg',
  // help: '24x24/common/help.svg',
  // menu: '24x24/common/menu.svg',
  // commonMore: '24x24/common/more.svg',
  // notifications: '24x24/common/notifications.svg',
  // pause: '24x24/common/pause.svg',
  // play: '24x24/common/play.svg',
  // search: '24x24/common/search.svg',
  // slash: '24x24/common/slash.svg',
  // sort: '24x24/common/sort.svg',
  // tag: '24x24/common/tag.svg',
  // upload: '24x24/common/upload.svg',
  // user: '24x24/common/user.svg',
  // xCircle: '24x24/common/x-circle.svg',
  // zap: '24x24/common/zap.svg',
  // arrowUpCircle: '24x24/constructor/arrow-up-circle.svg',
  // askPhone: '24x24/constructor/ask phone.svg',
  // bracket: '24x24/constructor/bracket.svg',
  // delete: '24x24/constructor/delete.svg',
  // emoji: '24x24/constructor/emoji.svg',
  // horizontal: '24x24/constructor/horizontal.svg',
  // constructorPlus: '24x24/constructor/plus.svg',
  // constructorUrl: '24x24/constructor/url.svg',
  // constructorVertical: '24x24/constructor/vertical.svg',
  // dropDownClose: '24x24/drop-down/close.svg',
  // dropDownCopyBot: '24x24/drop-down/copy-bot.svg',
  // dropDownEdit: '24x24/drop-down/edit.svg',
  // dropDownInfo: '24x24/drop-down/info.svg',
  // dropDownLink: '24x24/drop-down/link.svg',
  // dropDownLogOut: '24x24/drop-down/log-out.svg',
  // dropDownNotificationsSetting: '24x24/drop-down/notifications-setting.svg',
  // dropDownPayment: '24x24/drop-down/payment.svg',
  // dropDownSettings: '24x24/drop-down/settings.svg',
  // dropDownShare: '24x24/drop-down/share.svg',
  // dropDownTrash: '24x24/drop-down/trash.svg',
  // markdownBold: '24x24/markdown/bold.svg',
  // markdownCode: '24x24/markdown/code.svg',
  // markdownItalic: '24x24/markdown/italic.svg',
  // off: '24x24/radio-button/off.svg',
  // on: '24x24/radio-button/on.svg',
  // screenNavigationFit: '24x24/screen-navigation/fit.svg',
  // screenNavigationFullScreen: '24x24/screen-navigation/full-screen.svg',
  // screenNavigationMinus: '24x24/screen-navigation/minus.svg',
  // screenNavigationPage: '24x24/screen-navigation/page.svg',
  // screenNavigationPlus: '24x24/screen-navigation/plus.svg',
  // equalNot: '24x24/variables/equal-not.svg',
  // equalWithoutCase: '24x24/variables/equal-without-case.svg',
  // equal: '24x24/variables/equal.svg',
  // inLineWithoutCase: '24x24/variables/in-line-without-case.svg',
  // inLine: '24x24/variables/in-line.svg',
  // lessOrEqual: '24x24/variables/less-or-equal.svg',
  // less: '24x24/variables/less.svg',
  // moreOrEqual: '24x24/variables/more-or-equal.svg',
  // more: '24x24/variables/more.svg',
  // notInLineWithoutCase: '24x24/variables/not-in-line-without-case.svg',
  // notInLine: '24x24/variables/not-in-line.svg',
  // add: '36x36/add.svg',
  // alisaDefault: '40x40/alisa/default.svg',
  // alisaHover: '40x40/alisa/hover.svg',
  // alisaInactive: '40x40/alisa/inactive.svg',
  // facebookDefault: '40x40/facebook/default.svg',
  // facebookHover: '40x40/facebook/hover.svg',
  // facebookInactive: '40x40/facebook/inactive.svg',
  // googleDefault: '40x40/google/default.svg',
  // googleHover: '40x40/google/hover.svg',
  // googleInactive: '40x40/google/inactive.svg',
  // instaDefault: '40x40/insta/default.svg',
  // instaHover: '40x40/insta/hover.svg',
  // instaInactive: '40x40/insta/inactive.svg',
  // mailruDefault: '40x40/mailru/default.svg',
  // mailruHover: '40x40/mailru/hover.svg',
  // mailruInactive: '40x40/mailru/inactive.svg',
  // odnoklassnikiDefault: '40x40/odnoklassniki/default.svg',
  // odnoklassnikiHover: '40x40/odnoklassniki/hover.svg',
  // odnoklassnikiInactive: '40x40/odnoklassniki/inactive.svg',
  // telegramDefault: '40x40/telegram/default.svg',
  // telegramHover: '40x40/telegram/hover.svg',
  // telegramInactive: '40x40/telegram/inactive.svg',
  // twitterDefault: '40x40/twitter/default.svg',
  // twitterHover: '40x40/twitter/hover.svg',
};

export default IconMapping;

export type IconName = keyof typeof IconMapping;
