import {
  baseCell,
  switcherCell,
} from '../../components/table-cells/table-cells';

export const shareHeadStyle = {
  border: 'none',
  backgroundColor: '#ECEFFF',
  padding: '0',
  borderRadius: '0',
  fontFamily: 'Open Sans, sans-serif',
  fontWeight: '400',
  fontSize: '16px',
  ':last-of-type': {
    borderRadius: '0 10px 10px 0',
  },
};

export const rowStyleRef = {
  height: '72px',
  borderBottom: '.5px #CCD4E0 solid',
  ':hover': {
    backgroundColor: '#F8F9FB',
  },
  cursor: 'pointer',
};

export const cellStyle = {
  border: 'none',
  padding: '0',
  boxSizing: 'border-box',
  maxWidth: '168px',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
};

export const shareRows = [
  {
    id: 1,
    name: 'Leslie Alexander',
    mail: 'leslie@gmail.com',
    adm: true,
    shared: true,
    mailing: true,
    hands: false,
    stats: false,
    dialogs: true,
    crm: false,
    minilanding: true,
  },
  {
    id: 2,
    name: 'Leslie Genevieve',
    mail: 'leslieG@gmail.com',
    adm: false,
    shared: true,
    mailing: true,
    hands: false,
    stats: true,
    dialogs: false,
    crm: false,
    minilanding: true,
  },
  {
    id: 3,
    name: 'Baumtrok Vyacheslav',
    mail: 'me@vbaumtrok.com',
    adm: true,
    shared: false,
    mailing: true,
    hands: false,
    stats: false,
    dialogs: true,
    crm: true,
    minilanding: true,
  },
  {
    id: 4,
    name: 'Anton Antonov',
    mail: 'veryverylongemailvalue@gmail.com',
    adm: false,
    shared: true,
    mailing: false,
    hands: true,
    stats: false,
    dialogs: true,
    crm: false,
    minilanding: true,
  },
  {
    id: 5,
    name: 'Robert Kennedy',
    mail: 'leslie@gmail.com',
    adm: false,
    shared: true,
    mailing: true,
    hands: true,
    stats: false,
    dialogs: true,
    crm: false,
    minilanding: false,
  },
  {
    id: 6,
    name: 'Ivan Ivanov',
    mail: 'ivan@gmail.com',
    adm: false,
    shared: true,
    mailing: true,
    hands: false,
    stats: false,
    dialogs: true,
    crm: true,
    minilanding: true,
  },
  {
    id: 7,
    name: 'John Snow',
    mail: 'traitor@mail.com',
    adm: true,
    shared: true,
    mailing: true,
    hands: true,
    stats: false,
    dialogs: true,
    crm: true,
    minilanding: true,
  },
];

export const shareCols = [
  {
    id: 1,
    key: 'name',
    label: 'Имя',
    colStyle: { ...shareHeadStyle, width: '12%' },
    cellComponent: baseCell,
  },
  {
    id: 2,
    key: 'mail',
    label: 'Email',
    colStyle: { ...shareHeadStyle, width: '10%' },
    cellComponent: baseCell,
  },
  {
    id: 3,
    key: 'adm',
    label: 'Управление',
    colStyle: { ...shareHeadStyle, width: '10%' },
    cellComponent: switcherCell,
  },
  {
    id: 4,
    key: 'shared',
    label: 'Общий доступ',
    colStyle: { ...shareHeadStyle, width: '13%' },
    cellComponent: switcherCell,
  },
  {
    id: 5,
    key: 'mailing',
    label: 'Рассылка',
    colStyle: { ...shareHeadStyle, width: '9%' },
    cellComponent: switcherCell,
  },
  {
    id: 6,
    key: 'hands',
    label: 'Ручное упр.',
    colStyle: { ...shareHeadStyle, width: '10%' },
    cellComponent: switcherCell,
  },
  {
    id: 7,
    key: 'stats',
    label: 'Статистика',
    colStyle: { ...shareHeadStyle, width: '10%' },
    cellComponent: switcherCell,
  },
  {
    id: 8,
    key: 'dialogs',
    label: 'Диалоги',
    colStyle: { ...shareHeadStyle, width: '9%' },
    cellComponent: switcherCell,
  },
  {
    id: 9,
    key: 'crm',
    label: 'CRM',
    colStyle: { ...shareHeadStyle, width: '7%' },
    cellComponent: switcherCell,
  },
  {
    id: 10,
    key: 'minilanding',
    label: 'Минилендинг',
    colStyle: { ...shareHeadStyle, width: '10%' },
    cellComponent: switcherCell,
  },
];

export const shareTableModalButtons = [{ label: 'Удалить', value: 'del' }];
